### ISSUE TITLE
Ubuntu WSL/GCC: Tests don't run in debug, segfault

### ISSUE THREAD

**Issue by pirpyn** [jacobwilliams/slsqp#19]
This only happens on Ubuntu WSL

To reproduce
```bash
$ FoBiS.py build -f slsqp.fobis -mode tests-gnu-debug -t slsqp_test.f90 -force_compile  && ./bin/slsqp_test
[...]
Target src/tests/slsqp_test.f90 has been successfully built

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7fdb1d6f0d01 in ???
#1  0x7fdb1d6efed5 in ???
#2  0x7fdb1d51620f in ???
#3  0x7fffcc174fb8 in ???
Segmentation fault (core dumped)
```
Inspecting with GDB the problem occurs at slsqp_module.f90:398
```fortran
call me%f(x,f,cvec)
```
Could it be a compiler bug that fails to get me%f correctly ?

**Comment by pirpyn** [comment]
Since it only happens on WSL, this is likely a compiler error.
Nevertheless it could be useful to investigate it to produces a MCVE to report to gcc.

**Comment by jacobwilliams** [comment]
Note: I have GitHub Actions set up now for testing. Probably we could add a WSL test?
